"""initial schema

Revision ID: 8534e459d40d
Revises: 
Create Date: 2026-09-01 23:03:17.963148
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'GIF', name='mediatype', native_enum=False, length=16), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('poster_storage_key', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_media_content_hash'), 'question_media', ['content_hash'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'REPEALED', name='rulestatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('admin_role', sa.Enum('CONTENT_AUTHOR', 'CONTENT_REVIEWER', 'ADMIN', 'SUPERADMIN', name='adminrole', native_enum=False, length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('practice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('B', 'A', 'A1', 'C', 'D', name='category', native_enum=False, length=8), nullable=False),
    sa.Column('topic', sa.Enum('GENERAL_RULES', 'ROAD_SIGNS', 'ROAD_MARKINGS', 'SIGNALS', 'INTERSECTIONS', 'MANOEUVRING', 'SPEED_DISTANCE', 'OVERTAKING', 'STOPPING_PARKING', 'VULNERABLE_USERS', 'RAILWAY_CROSSINGS', 'MOTORWAYS_SPECIAL', 'VEHICLE_CONDITION', 'TRANSPORT_OF_PEOPLE_CARGO', 'EMERGENCIES_FIRST_AID', name='topic', native_enum=False, length=48), nullable=True),
    sa.Column('source', sa.Enum('TOPIC', 'MIXED', 'MISTAKES', 'SIGN_TRAINER', 'DIAGNOSTIC', name='practicesource', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('question_media_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'language', name='uq_media_translation_lang')
    )
    op.create_index(op.f('ix_question_media_translations_media_id'), 'question_media_translations', ['media_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('B', 'A', 'A1', 'C', 'D', name='category', native_enum=False, length=8), nullable=False),
    sa.Column('topic', sa.Enum('GENERAL_RULES', 'ROAD_SIGNS', 'ROAD_MARKINGS', 'SIGNALS', 'INTERSECTIONS', 'MANOEUVRING', 'SPEED_DISTANCE', 'OVERTAKING', 'STOPPING_PARKING', 'VULNERABLE_USERS', 'RAILWAY_CROSSINGS', 'MOTORWAYS_SPECIAL', 'VEHICLE_CONDITION', 'TRANSPORT_OF_PEOPLE_CARGO', 'EMERGENCIES_FIRST_AID', name='topic', native_enum=False, length=48), nullable=False),
    sa.Column('subtopic', sa.String(length=255), nullable=True),
    sa.Column('is_sign_question', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['question_versions.id'], name='fk_question_current_version', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_table('rule_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'language', name='uq_rule_translation_lang')
    )
    op.create_index(op.f('ix_rule_translations_rule_id'), 'rule_translations', ['rule_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ranking_name', sa.String(length=255), nullable=True),
    sa.Column('show_on_ranking', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('B', 'A', 'A1', 'C', 'D', name='category', native_enum=False, length=8), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('target_exam_date', sa.Date(), nullable=True),
    sa.Column('daily_goal', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('question_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version', name='uq_question_version')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_options_question_version_id'), 'answer_options', ['question_version_id'], unique=False)
    op.create_table('question_version_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_version_id', 'rule_id', name='uq_qv_rule')
    )
    op.create_index(op.f('ix_question_version_rules_question_version_id'), 'question_version_rules', ['question_version_id'], unique=False)
    op.create_index(op.f('ix_question_version_rules_rule_id'), 'question_version_rules', ['rule_id'], unique=False)
    op.create_table('question_version_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('REFERENCE', 'DIAGRAM_SOURCE', 'MEDIA_SOURCE', 'OTHER', name='sourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_version_sources_question_version_id'), 'question_version_sources', ['question_version_id'], unique=False)
    op.create_table('question_version_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('short_explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_version_id', 'language', name='uq_qv_translation_lang')
    )
    op.create_index(op.f('ix_question_version_translations_question_version_id'), 'question_version_translations', ['question_version_id'], unique=False)
    op.create_table('answer_option_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('answer_option_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_option_id'], ['answer_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_option_id', 'language', name='uq_option_translation_lang')
    )
    op.create_index(op.f('ix_answer_option_translations_answer_option_id'), 'answer_option_translations', ['answer_option_id'], unique=False)
    op.create_table('practice_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_session_id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_id', sa.String(length=36), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['answer_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answers_practice_session_id'), 'practice_answers', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_practice_answers_question_version_id'), 'practice_answers', ['question_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_answers_question_version_id'), table_name='practice_answers')
    op.drop_index(op.f('ix_practice_answers_practice_session_id'), table_name='practice_answers')
    op.drop_table('practice_answers')
    op.drop_index(op.f('ix_answer_option_translations_answer_option_id'), table_name='answer_option_translations')
    op.drop_table('answer_option_translations')
    op.drop_index(op.f('ix_question_version_translations_question_version_id'), table_name='question_version_translations')
    op.drop_table('question_version_translations')
    op.drop_index(op.f('ix_question_version_sources_question_version_id'), table_name='question_version_sources')
    op.drop_table('question_version_sources')
    op.drop_index(op.f('ix_question_version_rules_rule_id'), table_name='question_version_rules')
    op.drop_index(op.f('ix_question_version_rules_question_version_id'), table_name='question_version_rules')
    op.drop_table('question_version_rules')
    op.drop_index(op.f('ix_answer_options_question_version_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_rule_translations_rule_id'), table_name='rule_translations')
    op.drop_table('rule_translations')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_media_translations_media_id'), table_name='question_media_translations')
    op.drop_table('question_media_translations')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_question_media_content_hash'), table_name='question_media')
    op.drop_table('question_media')
    # ### end Alembic commands ###
