"""mock exam

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-01 23:26:24.275458
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('B', 'A', 'A1', 'C', 'D', name='category', native_enum=False, length=8), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='mockstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exam_config_version', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('pass_correct', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('answered_count', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_attempts_status'), 'mock_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_mock_attempts_user_id'), 'mock_attempts', ['user_id'], unique=False)
    # At most one in-progress attempt per user (atomic guard; status persists by member name).
    op.create_index(
        'uq_mock_one_in_progress_per_user',
        'mock_attempts',
        ['user_id'],
        unique=True,
        sqlite_where=sa.text("status = 'IN_PROGRESS'"),
        postgresql_where=sa.text("status = 'IN_PROGRESS'"),
    )
    op.create_table('mock_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mock_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mock_attempt_id'], ['mock_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_attempt_id', 'position', name='uq_mock_question_position'),
    sa.UniqueConstraint('mock_attempt_id', 'question_version_id', name='uq_mock_question_version')
    )
    op.create_index(op.f('ix_mock_questions_mock_attempt_id'), 'mock_questions', ['mock_attempt_id'], unique=False)
    op.create_index(op.f('ix_mock_questions_question_version_id'), 'mock_questions', ['question_version_id'], unique=False)
    op.create_table('mock_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mock_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_id', sa.String(length=36), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marked_for_review', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mock_attempt_id'], ['mock_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['answer_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_attempt_id', 'question_version_id', name='uq_mock_answer_version')
    )
    op.create_index(op.f('ix_mock_answers_mock_attempt_id'), 'mock_answers', ['mock_attempt_id'], unique=False)
    op.create_index(op.f('ix_mock_answers_question_version_id'), 'mock_answers', ['question_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_answers_question_version_id'), table_name='mock_answers')
    op.drop_index(op.f('ix_mock_answers_mock_attempt_id'), table_name='mock_answers')
    op.drop_table('mock_answers')
    op.drop_index(op.f('ix_mock_questions_question_version_id'), table_name='mock_questions')
    op.drop_index(op.f('ix_mock_questions_mock_attempt_id'), table_name='mock_questions')
    op.drop_table('mock_questions')
    op.drop_index(op.f('ix_mock_attempts_user_id'), table_name='mock_attempts')
    op.drop_index('uq_mock_one_in_progress_per_user', table_name='mock_attempts')
    op.drop_index(op.f('ix_mock_attempts_status'), table_name='mock_attempts')
    op.drop_table('mock_attempts')
    # ### end Alembic commands ###
