"""admin studio + reports

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-01 23:57:42.917009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_events_action'), 'admin_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_actor_user_id'), 'admin_audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_entity_id'), 'admin_audit_events', ['entity_id'], unique=False)
    op.create_table('content_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Enum('WRONG_ANSWER', 'UNCLEAR_EXPLANATION', 'IMAGE_PROBLEM', 'OUTDATED_RULE', 'TYPO', 'OTHER', name='reportreason', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'RESOLVED', 'REJECTED', name='reportstatus', native_enum=False, length=16), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_question_version_id'), 'content_reports', ['question_version_id'], unique=False)
    op.create_index(op.f('ix_content_reports_status'), 'content_reports', ['status'], unique=False)
    op.create_index(op.f('ix_content_reports_user_id'), 'content_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_reports_user_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_status'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_question_version_id'), table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_index(op.f('ix_admin_audit_events_entity_id'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_actor_user_id'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_action'), table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    # ### end Alembic commands ###
