"""slice4 mistakes ranking readiness stats

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-02 00:51:42.100075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('INSUFFICIENT_DATA', 'INITIAL', 'READY_ESTIMATE', name='readinessstate', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('exam_ready', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_readiness_user')
    )
    op.create_index(op.f('ix_readiness_snapshots_user_id'), 'readiness_snapshots', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_streak_user')
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=False)
    op.create_table('student_daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('answers_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stat_date', name='uq_daily_stat_user_date')
    )
    op.create_index(op.f('ix_student_daily_stats_user_id'), 'student_daily_stats', ['user_id'], unique=False)
    op.create_table('user_points_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('PRACTICE_UNIQUE', 'MISTAKE_RECOVERY', 'MOCK_CORRECT', 'MOCK_BONUS', 'DAILY_CONSISTENCY', name='pointssource', native_enum=False, length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'ref_type', 'ref_id', name='uq_ledger_idempotent')
    )
    op.create_index('ix_ledger_user_local_date', 'user_points_ledger', ['user_id', 'local_date'], unique=False)
    op.create_index('ix_ledger_local_date', 'user_points_ledger', ['local_date'], unique=False)
    op.create_index(op.f('ix_user_points_ledger_user_id'), 'user_points_ledger', ['user_id'], unique=False)
    op.create_table('mistake_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('first_missed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_missed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('last_result', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_mistake_user_question')
    )
    op.create_index(op.f('ix_mistake_entries_question_id'), 'mistake_entries', ['question_id'], unique=False)
    op.create_index(op.f('ix_mistake_entries_resolved'), 'mistake_entries', ['resolved'], unique=False)
    op.create_index(op.f('ix_mistake_entries_user_id'), 'mistake_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistake_entries_user_id'), table_name='mistake_entries')
    op.drop_index(op.f('ix_mistake_entries_resolved'), table_name='mistake_entries')
    op.drop_index(op.f('ix_mistake_entries_question_id'), table_name='mistake_entries')
    op.drop_table('mistake_entries')
    op.drop_index(op.f('ix_user_points_ledger_user_id'), table_name='user_points_ledger')
    op.drop_index('ix_ledger_local_date', table_name='user_points_ledger')
    op.drop_index('ix_ledger_user_local_date', table_name='user_points_ledger')
    op.drop_table('user_points_ledger')
    op.drop_index(op.f('ix_student_daily_stats_user_id'), table_name='student_daily_stats')
    op.drop_table('student_daily_stats')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_readiness_snapshots_user_id'), table_name='readiness_snapshots')
    op.drop_table('readiness_snapshots')
    # ### end Alembic commands ###
