"""slice6 theory handbook catalogues

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-02 02:36:17.323095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controller_gestures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('animation_media_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['animation_media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['controller_gesture_versions.id'], name='fk_controller_gesture_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controller_gestures_code'), 'controller_gestures', ['code'], unique=False)
    op.create_table('road_markings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('marking_group', sa.Enum('HORIZONTAL', 'VERTICAL', 'TEMPORARY', name='roadmarkinggroup', native_enum=False, length=16), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['road_marking_versions.id'], name='fk_road_marking_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_markings_code'), 'road_markings', ['code'], unique=False)
    op.create_index(op.f('ix_road_markings_marking_group'), 'road_markings', ['marking_group'], unique=False)
    op.create_table('road_signs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('official_code', sa.String(length=32), nullable=False),
    sa.Column('family', sa.Enum('WARNING', 'PRIORITY', 'PROHIBITORY', 'MANDATORY', 'INFORMATION', 'SERVICE', 'ADDITIONAL_PLATE', name='roadsignfamily', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['road_sign_versions.id'], name='fk_road_sign_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_signs_family'), 'road_signs', ['family'], unique=False)
    op.create_index(op.f('ix_road_signs_official_code'), 'road_signs', ['official_code'], unique=False)
    op.create_table('theory_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('SECTION', 'ARTICLE', 'SIGN', 'MARKING', 'GESTURE', 'LIGHT', 'RULE', name='theorytargettype', native_enum=False, length=16), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_theory_favorite_target')
    )
    op.create_index(op.f('ix_theory_favorites_user_id'), 'theory_favorites', ['user_id'], unique=False)
    op.create_table('theory_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('SECTION', 'ARTICLE', 'SIGN', 'MARKING', 'GESTURE', 'LIGHT', 'RULE', name='theorytargettype', native_enum=False, length=16), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('VIEWED', 'PRACTISED', 'MASTERED', name='theoryprogressstate', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_theory_progress_target')
    )
    op.create_index(op.f('ix_theory_progress_user_id'), 'theory_progress', ['user_id'], unique=False)
    op.create_table('theory_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.Enum('GENERAL_RULES', 'ROAD_SIGNS', 'ROAD_MARKINGS', 'SIGNALS', 'INTERSECTIONS', 'MANOEUVRING', 'SPEED_DISTANCE', 'OVERTAKING', 'STOPPING_PARKING', 'VULNERABLE_USERS', 'RAILWAY_CROSSINGS', 'MOTORWAYS_SPECIAL', 'VEHICLE_CONDITION', 'TRANSPORT_OF_PEOPLE_CARGO', 'EMERGENCIES_FIRST_AID', name='topic', native_enum=False, length=48), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('icon_media_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['icon_media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theory_sections_slug'), 'theory_sections', ['slug'], unique=True)
    op.create_table('traffic_light_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('MAIN', 'ARROW_SECTION', 'FLASHING', 'PEDESTRIAN', 'RAILWAY', 'SPECIAL', name='trafficlightkind', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['traffic_light_state_versions.id'], name='fk_traffic_light_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_light_states_kind'), 'traffic_light_states', ['kind'], unique=False)
    op.create_table('controller_gesture_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gesture_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('animation_media_id', sa.String(length=36), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['animation_media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gesture_id'], ['controller_gestures.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gesture_id', 'version', name='uq_controller_gesture_version')
    )
    op.create_index(op.f('ix_controller_gesture_versions_gesture_id'), 'controller_gesture_versions', ['gesture_id'], unique=False)
    op.create_table('road_marking_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_marking_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['road_marking_id'], ['road_markings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_marking_id', 'version', name='uq_road_marking_version')
    )
    op.create_index(op.f('ix_road_marking_versions_road_marking_id'), 'road_marking_versions', ['road_marking_id'], unique=False)
    op.create_table('road_sign_question_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_sign_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['road_sign_id'], ['road_signs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_sign_id', 'question_id', name='uq_road_sign_question')
    )
    op.create_index(op.f('ix_road_sign_question_links_question_id'), 'road_sign_question_links', ['question_id'], unique=False)
    op.create_index(op.f('ix_road_sign_question_links_road_sign_id'), 'road_sign_question_links', ['road_sign_id'], unique=False)
    op.create_table('road_sign_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_sign_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['road_sign_id'], ['road_signs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_sign_id', 'version', name='uq_road_sign_version')
    )
    op.create_index(op.f('ix_road_sign_versions_road_sign_id'), 'road_sign_versions', ['road_sign_id'], unique=False)
    op.create_table('theory_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('LESSON', 'REFERENCE', 'QUICK_REF', 'COMMON_MISTAKE', name='theoryarticlekind', native_enum=False, length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['theory_article_versions.id'], name='fk_theory_article_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['section_id'], ['theory_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'slug', name='uq_theory_article_slug_in_section')
    )
    op.create_index(op.f('ix_theory_articles_section_id'), 'theory_articles', ['section_id'], unique=False)
    op.create_index(op.f('ix_theory_articles_slug'), 'theory_articles', ['slug'], unique=False)
    op.create_table('theory_section_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['theory_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'language', name='uq_theory_section_translation_lang')
    )
    op.create_index(op.f('ix_theory_section_translations_section_id'), 'theory_section_translations', ['section_id'], unique=False)
    op.create_table('traffic_light_state_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('light_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['light_id'], ['traffic_light_states.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_id', 'version', name='uq_traffic_light_version')
    )
    op.create_index(op.f('ix_traffic_light_state_versions_light_id'), 'traffic_light_state_versions', ['light_id'], unique=False)
    op.create_table('controller_gesture_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gesture_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gesture_version_id'], ['controller_gesture_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gesture_version_id', 'rule_id', name='uq_controller_gesture_rule')
    )
    op.create_index(op.f('ix_controller_gesture_rules_gesture_version_id'), 'controller_gesture_rules', ['gesture_version_id'], unique=False)
    op.create_index(op.f('ix_controller_gesture_rules_rule_id'), 'controller_gesture_rules', ['rule_id'], unique=False)
    op.create_table('controller_gesture_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gesture_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position_desc', sa.Text(), nullable=False),
    sa.Column('allowed', sa.Text(), nullable=False),
    sa.Column('forbidden', sa.Text(), nullable=False),
    sa.Column('memory_tip', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gesture_version_id'], ['controller_gesture_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gesture_version_id', 'language', name='uq_controller_gesture_translation_lang')
    )
    op.create_index(op.f('ix_controller_gesture_translations_gesture_version_id'), 'controller_gesture_translations', ['gesture_version_id'], unique=False)
    op.create_table('road_marking_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_marking_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['road_marking_version_id'], ['road_marking_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_marking_version_id', 'rule_id', name='uq_road_marking_rule')
    )
    op.create_index(op.f('ix_road_marking_rules_road_marking_version_id'), 'road_marking_rules', ['road_marking_version_id'], unique=False)
    op.create_index(op.f('ix_road_marking_rules_rule_id'), 'road_marking_rules', ['rule_id'], unique=False)
    op.create_table('road_marking_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_marking_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('can_cross', sa.Text(), nullable=True),
    sa.Column('can_stop_park', sa.Text(), nullable=True),
    sa.Column('conflict_rule', sa.Text(), nullable=True),
    sa.Column('exam_trap', sa.Text(), nullable=True),
    sa.Column('memory_tip', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['road_marking_version_id'], ['road_marking_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_marking_version_id', 'language', name='uq_road_marking_translation_lang')
    )
    op.create_index(op.f('ix_road_marking_translations_road_marking_version_id'), 'road_marking_translations', ['road_marking_version_id'], unique=False)
    op.create_table('road_sign_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_sign_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['road_sign_version_id'], ['road_sign_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_sign_version_id', 'rule_id', name='uq_road_sign_rule')
    )
    op.create_index(op.f('ix_road_sign_rules_road_sign_version_id'), 'road_sign_rules', ['road_sign_version_id'], unique=False)
    op.create_index(op.f('ix_road_sign_rules_rule_id'), 'road_sign_rules', ['rule_id'], unique=False)
    op.create_table('road_sign_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('road_sign_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('driver_action', sa.Text(), nullable=False),
    sa.Column('important', sa.Text(), nullable=True),
    sa.Column('exam_trap', sa.Text(), nullable=True),
    sa.Column('memory_tip', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['road_sign_version_id'], ['road_sign_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('road_sign_version_id', 'language', name='uq_road_sign_translation_lang')
    )
    op.create_index(op.f('ix_road_sign_translations_road_sign_version_id'), 'road_sign_translations', ['road_sign_version_id'], unique=False)
    op.create_table('theory_article_question_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['theory_articles.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'question_id', name='uq_theory_article_question')
    )
    op.create_index(op.f('ix_theory_article_question_links_article_id'), 'theory_article_question_links', ['article_id'], unique=False)
    op.create_index(op.f('ix_theory_article_question_links_question_id'), 'theory_article_question_links', ['question_id'], unique=False)
    op.create_table('theory_article_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEEDS_REVIEW', 'REVIEWED', 'PUBLISHED', 'NEEDS_REVERIFICATION', 'SUPERSEDED', 'ARCHIVED', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('hero_media_id', sa.String(length=36), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('authored_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['theory_articles.id'], ),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hero_media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'version', name='uq_theory_article_version')
    )
    op.create_index(op.f('ix_theory_article_versions_article_id'), 'theory_article_versions', ['article_id'], unique=False)
    op.create_table('traffic_light_state_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('light_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['light_version_id'], ['traffic_light_state_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_version_id', 'rule_id', name='uq_traffic_light_rule')
    )
    op.create_index(op.f('ix_traffic_light_state_rules_light_version_id'), 'traffic_light_state_rules', ['light_version_id'], unique=False)
    op.create_index(op.f('ix_traffic_light_state_rules_rule_id'), 'traffic_light_state_rules', ['rule_id'], unique=False)
    op.create_table('traffic_light_state_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('light_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('movement_permitted', sa.Text(), nullable=True),
    sa.Column('direction_permitted', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('typical_exam_situation', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['light_version_id'], ['traffic_light_state_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_version_id', 'language', name='uq_traffic_light_translation_lang')
    )
    op.create_index(op.f('ix_traffic_light_state_translations_light_version_id'), 'traffic_light_state_translations', ['light_version_id'], unique=False)
    op.create_table('theory_article_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['theory_article_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_version_id', 'rule_id', name='uq_theory_article_rule')
    )
    op.create_index(op.f('ix_theory_article_rules_article_version_id'), 'theory_article_rules', ['article_version_id'], unique=False)
    op.create_index(op.f('ix_theory_article_rules_rule_id'), 'theory_article_rules', ['rule_id'], unique=False)
    op.create_table('theory_article_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_version_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['theory_article_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_version_id', 'language', name='uq_theory_article_translation_lang')
    )
    op.create_index(op.f('ix_theory_article_translations_article_version_id'), 'theory_article_translations', ['article_version_id'], unique=False)
    op.create_table('theory_content_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_version_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'RULE_CALLOUT', 'IMAGE', 'ANIMATION', 'DIAGRAM', 'COMPARISON', 'WARNING', 'MEMORY_TIP', 'TABLE', 'EXAMPLE', 'PRACTICE_LINK', name='theoryblocktype', native_enum=False, length=32), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('ref_question_id', sa.String(length=36), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['theory_article_versions.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['question_media.id'], ),
    sa.ForeignKeyConstraint(['ref_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theory_content_blocks_article_version_id'), 'theory_content_blocks', ['article_version_id'], unique=False)
    op.create_table('theory_content_block_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', name='language', native_enum=False, length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['theory_content_blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'language', name='uq_theory_block_translation_lang')
    )
    op.create_index(op.f('ix_theory_content_block_translations_block_id'), 'theory_content_block_translations', ['block_id'], unique=False)
    # Batch mode: SQLite cannot ALTER COLUMN in place (recreates the table). Adds the
    # optional Theory-target columns and relaxes question_version_id to nullable so the
    # single report queue can hold both question and theory reports (docs/spec/14).
    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theory_target_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('theory_target_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('question_version_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_content_reports_theory_target_id'), ['theory_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reports_theory_target_type'), ['theory_target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_reports_theory_target_type'))
        batch_op.drop_index(batch_op.f('ix_content_reports_theory_target_id'))
        batch_op.alter_column('question_version_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('theory_target_id')
        batch_op.drop_column('theory_target_type')
    op.drop_index(op.f('ix_theory_content_block_translations_block_id'), table_name='theory_content_block_translations')
    op.drop_table('theory_content_block_translations')
    op.drop_index(op.f('ix_theory_content_blocks_article_version_id'), table_name='theory_content_blocks')
    op.drop_table('theory_content_blocks')
    op.drop_index(op.f('ix_theory_article_translations_article_version_id'), table_name='theory_article_translations')
    op.drop_table('theory_article_translations')
    op.drop_index(op.f('ix_theory_article_rules_rule_id'), table_name='theory_article_rules')
    op.drop_index(op.f('ix_theory_article_rules_article_version_id'), table_name='theory_article_rules')
    op.drop_table('theory_article_rules')
    op.drop_index(op.f('ix_traffic_light_state_translations_light_version_id'), table_name='traffic_light_state_translations')
    op.drop_table('traffic_light_state_translations')
    op.drop_index(op.f('ix_traffic_light_state_rules_rule_id'), table_name='traffic_light_state_rules')
    op.drop_index(op.f('ix_traffic_light_state_rules_light_version_id'), table_name='traffic_light_state_rules')
    op.drop_table('traffic_light_state_rules')
    op.drop_index(op.f('ix_theory_article_versions_article_id'), table_name='theory_article_versions')
    op.drop_table('theory_article_versions')
    op.drop_index(op.f('ix_theory_article_question_links_question_id'), table_name='theory_article_question_links')
    op.drop_index(op.f('ix_theory_article_question_links_article_id'), table_name='theory_article_question_links')
    op.drop_table('theory_article_question_links')
    op.drop_index(op.f('ix_road_sign_translations_road_sign_version_id'), table_name='road_sign_translations')
    op.drop_table('road_sign_translations')
    op.drop_index(op.f('ix_road_sign_rules_rule_id'), table_name='road_sign_rules')
    op.drop_index(op.f('ix_road_sign_rules_road_sign_version_id'), table_name='road_sign_rules')
    op.drop_table('road_sign_rules')
    op.drop_index(op.f('ix_road_marking_translations_road_marking_version_id'), table_name='road_marking_translations')
    op.drop_table('road_marking_translations')
    op.drop_index(op.f('ix_road_marking_rules_rule_id'), table_name='road_marking_rules')
    op.drop_index(op.f('ix_road_marking_rules_road_marking_version_id'), table_name='road_marking_rules')
    op.drop_table('road_marking_rules')
    op.drop_index(op.f('ix_controller_gesture_translations_gesture_version_id'), table_name='controller_gesture_translations')
    op.drop_table('controller_gesture_translations')
    op.drop_index(op.f('ix_controller_gesture_rules_rule_id'), table_name='controller_gesture_rules')
    op.drop_index(op.f('ix_controller_gesture_rules_gesture_version_id'), table_name='controller_gesture_rules')
    op.drop_table('controller_gesture_rules')
    op.drop_index(op.f('ix_traffic_light_state_versions_light_id'), table_name='traffic_light_state_versions')
    op.drop_table('traffic_light_state_versions')
    op.drop_index(op.f('ix_theory_section_translations_section_id'), table_name='theory_section_translations')
    op.drop_table('theory_section_translations')
    op.drop_index(op.f('ix_theory_articles_slug'), table_name='theory_articles')
    op.drop_index(op.f('ix_theory_articles_section_id'), table_name='theory_articles')
    op.drop_table('theory_articles')
    op.drop_index(op.f('ix_road_sign_versions_road_sign_id'), table_name='road_sign_versions')
    op.drop_table('road_sign_versions')
    op.drop_index(op.f('ix_road_sign_question_links_road_sign_id'), table_name='road_sign_question_links')
    op.drop_index(op.f('ix_road_sign_question_links_question_id'), table_name='road_sign_question_links')
    op.drop_table('road_sign_question_links')
    op.drop_index(op.f('ix_road_marking_versions_road_marking_id'), table_name='road_marking_versions')
    op.drop_table('road_marking_versions')
    op.drop_index(op.f('ix_controller_gesture_versions_gesture_id'), table_name='controller_gesture_versions')
    op.drop_table('controller_gesture_versions')
    op.drop_index(op.f('ix_traffic_light_states_kind'), table_name='traffic_light_states')
    op.drop_table('traffic_light_states')
    op.drop_index(op.f('ix_theory_sections_slug'), table_name='theory_sections')
    op.drop_table('theory_sections')
    op.drop_index(op.f('ix_theory_progress_user_id'), table_name='theory_progress')
    op.drop_table('theory_progress')
    op.drop_index(op.f('ix_theory_favorites_user_id'), table_name='theory_favorites')
    op.drop_table('theory_favorites')
    op.drop_index(op.f('ix_road_signs_official_code'), table_name='road_signs')
    op.drop_index(op.f('ix_road_signs_family'), table_name='road_signs')
    op.drop_table('road_signs')
    op.drop_index(op.f('ix_road_markings_marking_group'), table_name='road_markings')
    op.drop_index(op.f('ix_road_markings_code'), table_name='road_markings')
    op.drop_table('road_markings')
    op.drop_index(op.f('ix_controller_gestures_code'), table_name='controller_gestures')
    op.drop_table('controller_gestures')
    # ### end Alembic commands ###
